### PR TITLE
Release 2.0

### LINKED ISSUE #3254: 2.0 release
Create 2.0 release

- [X] ✅ Create 1.x branch (PR not needed)
- [x] ✅ Update master to **2.0-SNAPSHOT** 
- [x] ✅ Update branch from 1.x-SNAPSHOT to 1.x 
- [x] ✅ Remove release notes from branch 
- [x] ✅ update release notes & rename (inc. for 2.x)
- [x] ✅ Verify notebooks
- [x] ✅ Check UI 
- [x] ✅  Run CTS 
- [x] ✅  Run FVTs (this is only FVTs automated in the build process)
- [x] ⚠️  Check samples (only samples in the build)
- [x] ✅ Check swagger doc
- [x] ✅ Verify docker image/charts/compose
- [x] ✅ Launch release pipeline 
- [x] ✅ Approve release
- [x] Verify artifacts all on maven central (check for JCenter & other errors in release logs)
- [x] Create GitHub release
- [x] ensure any fixes ported to master

### LINKED ISSUE #3261: containers broken after transition from 2.0-SNAPSHOT to 2.0
The helm lab chart fails on the 2.0 branch (test PR not yet integrated) following the switch from 2.0-SNAPSHOT to 2.0

In the helm chart the version number is possibly not a quoted string in all places, leading to some auto type conversion, which, with just '2.0' is getting converted to the integer 2, and hence the wrong image being picked.

This didn't occur when -SNAPSHOT was part of the name......

However 1.8 seemed ok....  tbc..

For example
```
 Normal   Scheduled  <unknown>            default-scheduler       Successfully assigned default/lab-odpi-egeria-lab-ui-d9dd97d78-66cnm to 10.72.127.182
  Normal   Pulling    78s (x4 over 2m58s)  kubelet, 10.72.127.182  Pulling image "docker.io/planetf1/egeria:2"
  Warning  Failed     77s (x4 over 2m56s)  kubelet, 10.72.127.182  Failed to pull image "docker.io/planetf1/egeria:2": rpc error: code = Unknown desc = Error reading manifest 2 in docker.io/planetf1/egeria: manifest unknown: manifest unknown
  Warning  Failed     77s (x4 over 2m56s)  kubelet, 10.72.127.182  Error: ErrImagePull
  Normal   BackOff    53s (x6 over 2m56s)  kubelet, 10.72.127.182  Back-off pulling image "docker.io/planetf1/egeria:2"
  Warning  Failed     39s (x7 over 2m56s)  kubelet, 10.72.127.182  Error: ImagePullBackOff
```
Relates to: #3254

### PR DESCRIPTION
**Pull request by planetf1**
Final Release changes for 2.0
 - replaces release notes with master
 - updates version to 2.0
 - Fixes helm charts (bad version for docker image)
 - ensures FVTs run

Replaces #3256 

Partially fixes #3254
Fixes #3261

### CODE REVIEW

**Comment by planetf1** [comment]
This is now ready to be merged to create the 2.0 release

The issue has more details on progress and outstanding tasks (including updating the 2.0 release notes in master)

File: open-metadata-implementation/platform-services/platform-services-server/src/main/java/org/odpi/openmetadata/platformservices/server/OMAGServerPlatformOriginServices.java [hunk 1]
```diff
@@ -8,7 +8,7 @@
  */
 public class OMAGServerPlatformOriginServices
 {
-    final String   implementationOrigin = "ODPi Egeria OMAG Server Platform (version 2.0-SNAPSHOT)\n";
+    final String   implementationOrigin = "ODPi Egeria OMAG Server Platform (version 2.0)\n";
```
Comment (bogdan-sava) [inline open-metadata-implementation/platform-services/platform-services-server/src/main/java/org/odpi/openmetadata/platformservices/server/OMAGServerPlatformOriginServices.java:11]: Don't like this hardcoding in the java file.
Maybe use in the future getClass().getPackage().getImplementationVersion(), of course we need to have the version in the package also something like maven-jar-plugin need to be used.

However, this is not a stopper for release.

File: open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/fvt/FVTConstants.java [hunk 2]
```diff
@@ -8,7 +8,7 @@
 public class FVTConstants
 {
     public static final String USERID = "erinoverview";
-    public static final String DEFAULT_URL = "https://localhost:9443";
+    public static final String DEFAULT_URL = "https://localhost:9444";
```
Comment (davidradl) [inline open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/fvt/FVTConstants.java:11]: Why are we changing the port here as it then does not match the ports we set up in postman collections which set up  for cocoMDS1 and 4?

File: release-notes/README.md [hunk 3]
```diff
@@ -3,113 +3,7 @@
...
-    * Project management of IT change
-    * IoT and large scale cohorts
-
-
-## Reporting issues
-
-If you discover an issue in the release you are using, we recommend
-first upgrading to the latest available release.  If this does not
-resolve the problem, please raise a new
-[git issue](https://github.com/odpi/egeria).
```
Comment (davidradl) [inline release-notes/README.md:112]: I am wondering why the release notes are not appended to this readme, as before. Are we moving the release notes out of github?

File: open-metadata-implementation/platform-services/platform-services-server/src/main/java/org/odpi/openmetadata/platformservices/server/OMAGServerPlatformOriginServices.java (hunk 1 above)
Comment (planetf1) [reply open-metadata-implementation/platform-services/platform-services-server/src/main/java/org/odpi/openmetadata/platformservices/server/OMAGServerPlatformOriginServices.java:11]: Yes I'd agree with that sentiment. 

We want to report the maven /project version here, and currently we don't add it in to the manifest.
```
 Manifest-Version: 1.0
 Created-By: Maven Jar Plugin 3.2.0
 Build-Jdk-Spec: 14
```
we'd need to add Implementation-Version

I opened up #940 ages ago to look at adding this/other info -- so let's continue the discussion there & if we can think how to get rid of it in more places the better --

Indeed not specific to this release

File: open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/fvt/FVTConstants.java (hunk 2 above)
Comment (planetf1) [reply open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/fvt/FVTConstants.java:11]: * I agree with your point about consistency
* In our samples/tests we tend not to document the 'required' configuration to run them. The best we tend to have (IMO) is the 'coco pharma' environment which a) is coherent and b) I know is being used by others even to test clients against and c) is how I test much of the release currently .The master template I used for this was generally the coco pharma notebook diagrams.  I also accept that a test is quite different to a tutorial - the requirement is more just 'I can run it'.
* In the notebooks, both cocoMDS1 and cocoMDS4 are on the 'data lake' omag server platform. Under 'common' the default URL for the data lake platform is defined as `dataLakePlatformURL  = os.environ.get('dataLakePlatformURL', 'https://localhost:9444')` - hence why the default setting.
* So this means at least if running a comparable coco setup locally, the FVT's will 'just work' - a placeholder for further automation
* From a search I couldn't find explicit use of the coco servers/platforms in the postman collections/environment for the dojo. Geared towards a developer role it's a more manual approach. The reason for changing the test above is if it looks like coco, and smells like coco, it is coco ;-)
* In #426 I've been looking at options to automate - I plan to create a new PR (on 2.1+) for that, which will require changing the parm handling here to accept input parms (in addition) - for a single server environment, which is IMO quite different to coco pharma. Along with this we'll add docs, and this would superceded any change similar to this

File: release-notes/README.md (hunk 3 above)
Comment (planetf1) [reply release-notes/README.md:112]: When we release we remove all of the notes (including the main readme) from the branch - it's the same as 1.8, 1.7 etc.

We can open up an issue to discuss a better approach, but the change here is aligned with what we've done previously.

The release notes will be updated in master (this still needs to be done - contributions welcome - seperate PR though as targets master)

**Comment by planetf1** [comment]
@davidradl - have responded to comments above. hope this explains the thinking. I think it's good to go, but if you disagree am open to change also :-)
