### PR TITLE
Release 1.6 : Fixes exception reporting by REST service layer

### LINKED ISSUE #2850: Release 1.6 candidate - CTS tests failing
Running CTS tests under k8s on the 1.6 branch 7ee41d1d76bfda41152887d73f986759dec155f4

Inmem:
```
Date of conformance test:          2020-04-02T13:29:15.741+0000
Number of tests that were run:     3957
Number of tests that failed:       1257
Number of tests that were skipped: 0
```
```
	id	name	description	profilePriority	conformanceStatus
0	0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	NOT_CONFORMANT
1	1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	NOT_CONFORMANT
2	2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	NOT_CONFORMANT
3	3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	NOT_CONFORMANT
5	5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
6	6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	NOT_CONFORMANT
7	7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	NOT_CONFORMANT
8	8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
9	9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	NOT_CONFORMANT
10	10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	UNKNOWN_STATUS
12	12	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
13	13	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
14	14	Relationship advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT

```

### PR DESCRIPTION
**Pull request by planetf1**
Signed-off-by: Graham Wallis <graham_wallis@uk.ibm.com>
Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

Backports CTS fix #2860 into 1.6
Prior backport made incorrectly (by me!)

Fixes #2850

### CODE REVIEW

File: open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/rest/server/OMRSRepositoryRESTServices.java [hunk 1]
```diff
@@ -8005,13 +8005,13 @@ private void captureCheckedException(OMRSAPIResponse          response,
     {
         response.setRelatedHTTPCode(error.getReportedHTTPCode());
         response.setExceptionClassName(exceptionClassName);
```
Comment (mandy-chessell) [inline open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/rest/server/OMRSRepositoryRESTServices.java:8007]: Reordering of code properties may cause mistakes in the future and no longer follows consistent ordering.

Comment (planetf1) [reply open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/rest/server/OMRSRepositoryRESTServices.java:8007]: Opened #2874 to track independently. will go with the merge here for now
