### PR TITLE
#6022 Fix the metadataCollection.addTypeDef logic in OMRSRepositoryContentManager.processNewTypeDefEvent

### LINKED ISSUE #6022: [BUG] Parameters in class OMRSRepositoryContentManager.processNewAttributeTypeDefEvent maybe need to be updated.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the class OMRSRepositoryContentManager, here are two methods: **processNewAttributeTypeDefEvent** and **processNewTypeDefEvent**.

I believe that these two methods are similar, one will handle the EntityTypeDef, another will handle AttributeTypeDef.
You can see two lines codes from these two methods: line 2866, and 2677
I believe that the line 2866 in **processNewAttributeTypeDefEvent**, 
```
metadataCollection.addAttributeTypeDef(localServerUserId, attributeTypeDef);
```
the parameter **localServerUserId** should be changed to sourceName, just like line 2677 in **processNewTypeDefEvent**

### Expected Behavior

Class OMRSRepositoryContentManager
line 2866 in **processNewAttributeTypeDefEvent**, 
```
metadataCollection.addAttributeTypeDef(localServerUserId, attributeTypeDef);
```
the parameter **localServerUserId** should be changed to sourceName, just like line 2677 in **processNewTypeDefEvent**

### Alternatives

_No response_

### Any Further Information?

_No response_

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

### PR DESCRIPTION
**Pull request by gnahz-eh**
#6022 Fix the metadataCollection.addTypeDef logic in OMRSRepositoryContentManager.processNewTypeDefEvent.

# Description

In the class OMRSRepositoryContentManager, here are two methods: processNewAttributeTypeDefEvent and processNewTypeDefEvent.

I believe that these two methods are similar, one will handle the EntityTypeDef, another will handle AttributeTypeDef.
You can see two lines codes from these two methods: line 2866, and 2677
I believe that the line 2677 in processNewTypeDefEvent
```java
metadataCollection.addTypeDef(sourceName, typeDef);
```
the parameter **sourceName** should be changed to **localServerUserId**, just like line 2866 in processNewAttributeTypeDefEvent

Fixes #6022 

# How Has This Been Tested?

Yes have tested from my side. 

# Any additional notes for reviewers?

### CODE REVIEW

File: open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/localrepository/repositorycontentmanager/OMRSRepositoryContentManager.java [hunk 1]
```diff
@@ -2672,9 +2672,9 @@ public void processNewTypeDefEvent(String       sourceName,
                      * It throws TypeDefNotSupportedException if the typeDef is not supported and can not
                      * be dynamically defined by the local repository.
                      */
-                    if (! metadataCollection.verifyTypeDef(localServerUserId, typeDef))
+                    if (!metadataCollection.verifyTypeDef(localServerUserId, typeDef))
```
Comment (mandy-chessell) [inline open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/localrepository/repositorycontentmanager/OMRSRepositoryContentManager.java:2675]: Please add the space back in....

**Review by mandy-chessell — CHANGES_REQUESTED** [review]

File: open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/localrepository/repositorycontentmanager/OMRSRepositoryContentManager.java (hunk 1 above)
Comment (gnahZ-eH) [reply open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/localrepository/repositorycontentmanager/OMRSRepositoryContentManager.java]: Done.

**Review by mandy-chessell — APPROVED** [review]
