### PR TITLE
Fixes invalid type references for connector with subset of types

### LINKED ISSUE #2213: CTS NPEs on relationship endpoint EntityDef lookups
Came across a number of NullPointerExceptions in the (master) CTS as follows: under the `run()` method of the test classes below, the endpoint definitions of a relationship are retrieved but `repositoryHelper.getTypeDefByName(...)` fails with an NPE when the type definition is a supertype that is not implemented by the repository being tested. (For example, `ActorProfile` when the repository only implements `Person`; `Asset` when the repository only implements `Database`; `ComplexSchemaType` when the repository only implements `TabularSchemaType`, etc.)

Seems like another case where we should be retrieving the endpoint definitions of the relationship from the open type definitions themselves -- not from the repository under test?

Seen in all of the following:

- [ ] `TestSupportedRelationshipLifecycle`
- [ ] `TestSupportedRelationshipReidentify`
- [ ] `TestSupportedRelationshipPropertySearch`
- [ ] `TestSupportedRelationshipPropertyAdvancedSearch`

### PR DESCRIPTION
**Pull request by grahamwallis**
Fixes #2213

### CODE REVIEW

File: open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipPropertySearch.java [hunk 1]
```diff
@@ -264,22 +264,22 @@ protected void run(TestPhase phase) throws Exception
                 RepositoryConformanceProfileRequirement.CONSISTENT_TYPES.getRequirementId());
 
         String end1TypeDefName = relationshipDef.getEndDef1().getEntityType().getName();
+        EntityDef knownEnd1EntityDef = (EntityDef) repositoryHelper.getTypeDefByName(workPad.getLocalServerUserId(), end1TypeDefName);
         EntityDef end1EntityDef = entityDefs.get(end1TypeDefName);
```
Comment (cmgrote) [inline open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipPropertySearch.java]: This line seems to be the problematic one -- if the `end1TypeDefName` is for example `Asset` then the line before it will work fine (drawing from the open type definitions themselves) but this line (drawing from the entities that are implemented in a connector that does not implement the more abstract supertypes) will simply return `null` and the assertion on the very next line will therefore always fail since `end1EntityDef == null`.

File: open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipPropertySearch.java [hunk 2]
```diff
@@ -264,22 +264,22 @@ protected void run(TestPhase phase) throws Exception
...
-                RepositoryConformanceProfileRequirement.CONSISTENT_TYPES.getRequirementId());
+        verifyCondition( (end1EntityDef != null) && end1EntityDef.equals(knownEnd1EntityDef),
+                         assertion0,
+                         testTypeName + assertionMsg0,
+                         RepositoryConformanceProfileRequirement.CONSISTENT_TYPES.getProfileId(),
+                         RepositoryConformanceProfileRequirement.CONSISTENT_TYPES.getRequirementId());
 
         String end2TypeDefName = relationshipDef.getEndDef2().getEntityType().getName();
+        EntityDef knownEnd2EntityDef = (EntityDef) repositoryHelper.getTypeDefByName(workPad.getLocalServerUserId(), end2TypeDefName);
         EntityDef end2EntityDef = entityDefs.get(end2TypeDefName);
```
Comment (cmgrote) [inline open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipPropertySearch.java]: As above -- if the connector does not implement supertypes, this will return `null` for many relationships and the assertion just below will always fail as a result.

File: open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipSharingPropertySearch.java [hunk 3]
```diff
@@ -194,28 +197,24 @@ protected void run() throws Exception
...
-        verifyCondition((endTwoEntityDef.equals(knownEnd2EntityDef)),
-                assertion0,
-                testTypeName + assertionMsg0,
-                RepositoryConformanceProfileRequirement.CONSISTENT_TYPES.getProfileId(),
-                RepositoryConformanceProfileRequirement.CONSISTENT_TYPES.getRequirementId());
-
 
+        String end1TypeDefName = relationshipDef.getEndDef1().getEntityType().getName();
+        EntityDef knownEnd1EntityDef = (EntityDef) repositoryHelper.getTypeDefByName(workPad.getLocalServerUserId(), end1TypeDefName);
+        EntityDef end1EntityDef = entityDefs.get(end1TypeDefName);
```
Comment (cmgrote) [inline open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipSharingPropertySearch.java]: As above -- if the connector does not implement supertypes, this will return `null` for many relationships and the assertion just below will always fail as a result.

File: open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipSharingPropertySearch.java [hunk 4]
```diff
@@ -194,28 +197,24 @@ protected void run() throws Exception
...
+        verifyCondition( (end1EntityDef != null) && end1EntityDef.equals(knownEnd1EntityDef),
+                         assertion0,
+                         testTypeName + assertionMsg0,
+                         RepositoryConformanceProfileRequirement.CONSISTENT_TYPES.getProfileId(),
+                         RepositoryConformanceProfileRequirement.CONSISTENT_TYPES.getRequirementId());
+
+        String end2TypeDefName = relationshipDef.getEndDef2().getEntityType().getName();
+        EntityDef knownEnd2EntityDef = (EntityDef) repositoryHelper.getTypeDefByName(workPad.getLocalServerUserId(), end2TypeDefName);
+        EntityDef end2EntityDef = entityDefs.get(end2TypeDefName);
```
Comment (cmgrote) [inline open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipSharingPropertySearch.java]: As above -- if the connector does not implement supertypes, this will return `null` for many relationships and the assertion just below will always fail as a result.

Comment (grahamwallis) [reply open-metadata-conformance-suite/open-metadata-conformance-suite-server/src/main/java/org/odpi/openmetadata/conformance/tests/repository/instances/TestSupportedRelationshipSharingPropertySearch.java]: Please see additional commit "Refinements to relationship end type checks" which should resolve all the above. Sorry about that.
