### PR TITLE
issue 6358 fix (part of issue#326 Egeria UI)

### LINKED ISSUE #6358: [BUG] Code fix for Egerai UI issue326
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See EgeriaUI issue326 [https://github.com/odpi/egeria-react-ui/issues/326](https://github.com/odpi/egeria-react-ui/issues/326) 

### Expected Behavior

Expected that the isA Relation is successfully created .

### Steps To Reproduce

Testing Egeria 3.5 chart

    Egeria 3.5
    React UI 3.4

Logged in as garygeeke

Created a glossary 'a'
Created a category 'b'
Created two terms in above 'c', 'd'

All good to this point

I then tried to create a 'isA' relationship 'r' between c and d using the visual explorer

In the UI I got to the final screen, clicked create, and the page refreshed but no error/info was shown
In the log of the view server I see a Bad Request:
Full log at https://gist.github.com/e9bd7053cdcb056c85b24b53dbfcfa4e

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

The REST call error outs for a NULL point exception returning a Http code 400

### PR DESCRIPTION
**Pull request by odttlnt**
…set the symbolic name for the Enum property for the  status of the IsA Relationship in the relationship to instance properties
Fixes #326
Signed-off-by: Sachin Naik <91499691+odttlnt@users.noreply.github.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. Note that there should always be a related issue alongside a PR as that enables appropriate discussion.

Fixes #6358 
Fixes #[326](https://github.com/odpi/egeria-react-ui/issues/326) from EgeriaUI

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Consider any more risky areas that you need advice on.

# Any additional notes for reviewers?

### CODE REVIEW

File: open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/mappers/relationships/IsARelationshipMapper.java [hunk 1]
```diff
@@ -46,6 +46,7 @@ protected void mapRelationshipToInstanceProperties(IsA iSARelationship, Instance
         if (iSARelationship.getStatus() != null) {
             EnumPropertyValue enumPropertyValue = new EnumPropertyValue();
             enumPropertyValue.setOrdinal(iSARelationship.getStatus().getOrdinal());
+            enumPropertyValue.setSymbolicName(iSARelationship.getStatus().getName());
```
Comment (davidradl) [inline open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/mappers/relationships/IsARelationshipMapper.java:49]: I am not sure what difference this change I assume it is for the UI, so it displays the content more descriptively, if so then it should be on all of the mappers. It would make sense to have a method in SubjectAreaUtils similar to the other existing ones but for status:

it would be called like this:
   SubjectAreaUtils.setStatusPropertyInInstanceProperties(instanceProperties, iSARelationship.getStatus(), OpenMetadataAPIMapper.STATUS_PROPERTY_NAME);

Comment (odttlnt) [reply open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/mappers/relationships/IsARelationshipMapper.java:49]: The fix was not for giving descriptive information. In the flow of creating the IsA relationship in Egeria Core, there is code that accesses the symbolicName of the 'status' Enum. This threw a nullpointer exception and stopped the creation of the relationship. Adding this code will prevent the exception.
I will refactor this code to the utils class and update my pull req.

File: open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/mappers/relationships/IsARelationshipMapper.java [hunk 2]
```diff
@@ -44,9 +44,7 @@ protected void mapRelationshipToInstanceProperties(IsA iSARelationship, Instance
             SubjectAreaUtils.setStringPropertyInInstanceProperties(instanceProperties, iSARelationship.getSource(), OpenMetadataAPIMapper.SOURCE_PROPERTY_NAME);
         }
         if (iSARelationship.getStatus() != null) {
-            EnumPropertyValue enumPropertyValue = new EnumPropertyValue();
-            enumPropertyValue.setOrdinal(iSARelationship.getStatus().getOrdinal());
-            instanceProperties.setProperty(OpenMetadataAPIMapper.STATUS_PROPERTY_NAME, enumPropertyValue);
+            SubjectAreaUtils.setStatusPropertyInInstanceProperties(instanceProperties, iSARelationship.getStatus(), OpenMetadataAPIMapper.STATUS_PROPERTY_NAME);
         }
```
Comment (davidradl) [inline open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/server/mappers/relationships/IsARelationshipMapper.java:48]: I think the fix looks good - could you add this change for all the other relationships as well please. Or do you want to do this in a separate issue?

**Review by davidradl — APPROVED** [review]

**Comment by davidradl** [comment]
@planetf1 I cant merge this as there is an unresolved conversation that I cant see how to resolve. Any thoughts?

**Comment by planetf1** [comment]
I couldn't see any problem And was able to merge fine.
