### PR TITLE
Fixes #6335 incompatible URLs on data-manager's DisplayApplicationResource

### LINKED ISSUE #6335: [BUG] HTTP REST API URLs are not compatible on server and client
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Several apis looks broken because server and client urls are not compatible.

**CapabilityManagerClient / ITInfrastructureResource**

_client_

https://github.com/odpi/egeria/blob/2dacd35291e3ed523b6e7208065bf266d85bf7f0/open-metadata-implementation/access-services/it-infrastructure/it-infrastructure-client/src/main/java/org/odpi/openmetadata/accessservices/itinfrastructure/client/CapabilityManagerClient.java#L1040

_server_

https://github.com/odpi/egeria/blob/2dacd35291e3ed523b6e7208065bf266d85bf7f0/open-metadata-implementation/access-services/it-infrastructure/it-infrastructure-spring/src/main/java/org/odpi/openmetadata/accessservices/itinfrastructure/server/spring/ITInfrastructureResource.java#L1057

...and other urls in this two classes using `software-capabilities` vs `software-server-capabilities`

**DisplayApplicationClient / DisplayApplicationResource**

_client_ 

[`    private static final String schemaURLTemplatePrefix    = "/servers/{0}/open-metadata/access-services/data-manager/users/{1}/schemas";`](https://github.com/odpi/egeria/blob/41389b18f4427fe3c573a547fd1e7e62411457cf/open-metadata-implementation/access-services/data-manager/data-manager-client/src/main/java/org/odpi/openmetadata/accessservices/datamanager/client/DisplayApplicationClient.java#L30)

https://github.com/odpi/egeria/blob/41389b18f4427fe3c573a547fd1e7e62411457cf/open-metadata-implementation/access-services/data-manager/data-manager-client/src/main/java/org/odpi/openmetadata/accessservices/datamanager/client/DisplayApplicationClient.java#L1546

_server_
        
https://github.com/odpi/egeria/blob/2dacd35291e3ed523b6e7208065bf266d85bf7f0/open-metadata-implementation/access-services/data-manager/data-manager-spring/src/main/java/org/odpi/openmetadata/accessservices/datamanager/server/spring/DisplayApplicationResource.java#L23
        
https://github.com/odpi/egeria/blob/2dacd35291e3ed523b6e7208065bf266d85bf7f0/open-metadata-implementation/access-services/data-manager/data-manager-spring/src/main/java/org/odpi/openmetadata/accessservices/datamanager/server/spring/DisplayApplicationResource.java#L839

All other urls based on `schemaURLTemplatePrefix` are not compatible. The client using url ends with `schemas` but the server is not.

Invalid behaviour produces exceptions on API calls

```
PropertyServerException{reportedHTTPCode=503, reportingClassName='org.odpi.openmetadata.accessservices.datamanager.client.rest.DataManagerRESTClient', reportingActionDescription='findDatabaseTables', reportedErrorMessage='OMAG-COMMON-503-001 A client-side exception was received from API call findDatabaseTables to OMAG Server y at https://127.0.0.1:9443/.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpClientErrorException$NotFound was received by method findDatabaseTables from API call https://127.0.0.1:9443//servers/{0}/open-metadata/access-services/data-manager/users/{1}/databases/schemas/tables/by-search-string?startFrom={2}&pageSize={3} to server y on platform https://127.0.0.1:9443/.  The error message was 404 : "{"timestamp":"2022-03-22T15:26:59.764+00:00","status":404,"error":"Not Found","path":"/servers/y/open-metadata/access-services/data-manager/users/x/databases/schemas/tables/by-search-string"}"', reportedErrorMessageId='OMAG-COMMON-503-001', reportedErrorMessageParameters=[findDatabaseTables, y, https://127.0.0.1:9443/, CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpClientErrorException$NotFound was received by method findDatabaseTables from API call https://127.0.0.1:9443//servers/{0}/open-metadata/access-services/data-
manager/users/{1}/databases/schemas/tables/by-search-string?startFrom={2}&pageSize={3} to server y on platform https://127.0.0.1:9443/.  The error message was 404 : "{"timestamp":"2022-03-22T15:26:59.764+00:00","status":404,"error":"Not Found","path":"/servers/y/open-metadata/access-services/data-manager/users/x/databases/schemas/tables/by-search-string"}"], reportedSystemAction='The server has issued a call to the open metadata access service REST API in a remote server and has received an exception from the local client libraries.', reportedUserAction='Look for errors in the local server's console to understand and correct the source of the error.', reportedCaughtException=RESTServerException{reportedHTTPCode=503, reportingClassName='org.odpi.openmetadata.adapters.connectors.restclients.spring.SpringRESTClientConnector', reportingActionDescription='findDatabaseTables', errorMessage='CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpClientErrorException$NotFound was received by method findDatabaseTables from API call https://127.0.0.1:9443//servers/{0}/open-metadata/access-services/data-manager/users/{1}/databases/schemas/tables/by-search-string?startFrom={2}&pageSize={3} to server y on platform https://127.0.0.1:9443/.  The error message was 404 : "{"timestamp":"2022-03-22T15:26:59.764+00:00","status":404,"error":"Not Found","path":"/servers/y/open-metadata/access-services/data-manager/users/x/databases/schemas/tables/by-search-string"}"', reportedSystemAction='The client has issued a call to the open metadata access service REST API in a remote server and has received an exception from the local client libraries.', reportedUserAction='Review the error message to determine the cause of the error.  Check that the server is running an the URL is correct. Look for errors in the local server's console to understand and correct the cause of the error. Then rerun the request', reportedCaughtException=org.springframework.web.client.HttpClientErrorException$NotFound: 404 : "{"timestamp":"2022-03-22T15:26:59.764+00:00","status":404,"error":"Not Found","path":"/servers/y/open-metadata/access-services/data-manager/users/x/databases/schemas/tables/by-search-string"}"}, reportedCaughtExceptionClassName='org.odpi.openmetadata.adapters.connectors.restclients.ffdc.exceptions.RESTServerException', relatedProperties=null}
```

https://github.com/odpi/egeria/issues/6036 describes part of this bug.

### Expected Behavior

Client and server API's URLs are compatible

### Steps To Reproduce

_No response_

### Environment

```markdown
- Egeria: current master
- OS: n/a
- Java: n/a
- Browser (for UI issues): n/a
- Additional connectors and integration: n/a
```

### Any Further Information?

I could fix it asap. Should i do this on the client or server resource?

### PR DESCRIPTION
**Pull request by ykrkn**

### CODE REVIEW

File: open-metadata-implementation/access-services/data-manager/data-manager-spring/src/main/java/org/odpi/openmetadata/accessservices/datamanager/server/spring/DisplayApplicationResource.java [hunk 1]
```diff
@@ -836,7 +836,7 @@ public QueryResponse getQueryByGUID(@PathVariable String serverName,
      * UserNotAuthorizedException the user is not authorized to issue this request or
      * PropertyServerException    there is a problem reported in the open metadata server(s)
      */
-    @PostMapping(path = "/elements/{parentGUID}/data-containers")
+    @PostMapping(path = "/schemas/elements/{parentGUID}/data-containers")
```
Comment (davidradl) [inline open-metadata-implementation/access-services/data-manager/data-manager-spring/src/main/java/org/odpi/openmetadata/accessservices/datamanager/server/spring/DisplayApplicationResource.java:839]: this does not seem right , the comments say it is a form report or query but the end point now references schema which is different from form, report and query.

**Comment by davidradl** [comment]
From @mandy-chessell comment in the issue - this is still being developed.
 I suggest we wait until she has finished development. 
I notice that server side 
`    @PostMapping(path = "/data-containers/{dataContainerGUID}")`
`       @PostMapping(path = "/data-containers/by-search-string")`
`    @PostMapping(path = "/data-containers/by-name")`


these appear to clash on the url.

Also the client still references elements in its calls.

**Comment by mandy-chessell** [comment]
Looking at the code - changes need to be made to the server side to add the type name parameter to the method signature for both getDataContainerByName and findDataContainers.  The implementation for getDataContainerParent is completely missing.   I would suggest merging this PR since it fixes many of the URLs and the ones that still won't work are no worse than they were before.  updateDataContainer looks ok

**Review by mandy-chessell — APPROVED** [review]
